services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: openwebui-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U openwebui_user -d openwebui_db"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - openwebui-network

  # Ollama Service
  ollama:
    image: ollama/ollama:latest
    container_name: openwebui-ollama
    volumes:
      - ./volumes/ollama:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
      - OLLAMA_GPU_OVERHEAD=0          # Utilise plus de VRAM
      - OLLAMA_MAX_LOADED_MODELS=1     # Un seul modèle, toute la VRAM
      - OLLAMA_FLASH_ATTENTION=1       # Attention optimisée
      - OLLAMA_NUM_PARALLEL=8          # Parallélisation
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=all
      - OLLAMA_KEEP_ALIVE=-1        # Décharge après 5 minutes d'inactivité
    restart: unless-stopped
    networks:
      - openwebui-network
        # AJOUT GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # Open WebUI with PostgreSQL
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui-app
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_started
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - ENABLE_DIRECT_CONNECTIONS=True
    volumes:
      - ./volumes/openwebui:/app/backend/data
    restart: unless-stopped
    networks:
      - openwebui-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    

# MCPO - MCP to OpenAPI Proxy
  mcpo:
    image: ghcr.io/open-webui/mcpo:main
    container_name: avisol-mcpo
    ports:
      - "${MCPO_PORT:-8001}:8000"
    environment:
      - API_KEY=${MCPO_API_KEY}
    volumes:
      - ./config/mcpo-config.json:/app/config.json:ro
    command: [
      "--host", "0.0.0.0",
      "--port", "8000", 
      "--api-key", "${MCPO_API_KEY}",
      "--config", "/app/config.json"
    ]
    networks:
      - openwebui-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    

networks:
  openwebui-network:
    driver: bridge

volumes:
  postgres_data: