version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: openwebui-ollama
    ports:
      - "11434:11434"
    volumes:
      - ./volumes/ollama:/root/.ollama
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui-app
    depends_on:
      - ollama
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./volumes/openwebui:/app/backend/data
    restart: unless-stopped